# Generated by Django 2.2.1 on 2019-09-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
