# Generated by Django 2.2.1 on 2019-09-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20190911_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='p_id',
            new_name='p',
        ),
    ]
